baseURL = "https://eliekazan.github.io/"
languageCode = "en-us"
title = "Elie Kazan — Database Administrator & Computer Engineer"
paginate = 10
enableRobotsTXT = true

[params]
  description = "Database Administrator & Computer Engineer"
  author = "Elie Kazan"
  email = "elie@example.com"
  github = "https://github.com/eliekazan"
  linkedin = "https://linkedin.com/in/eliekazan"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
