baseURL = "https://eliekazan.github.io/"
languageCode = "en-us"
title = "Elie Kazan — Database Administrator & Computer Engineer"
paginate = 10
enableRobotsTXT = true

[params]
  description = "Database Administrator & Computer Engineer"
  author = "Elie Kazan"
  email = "kq8qwb8xm@mozmail.com"
  github = "https://github.com/elie-kazan"
  linkedin = "https://www.linkedin.com/in/elie-kazan-820957159/"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
